# Site wide configuration

title:            Make~Create~Innovate
locale:           en_US
# url:              http://localhost:4000
# {% highlight yaml %} url: http://peachyo.github.io url: http://localhost:4000 url: {% endhighlight %}


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: peachyo
  avatar: photo.png
  bio: "minimalist"
  email: risktechnocrat@gmail.com
  disqus-shortname: 
  twitter: #username
  facebook: #username
  google:
    plus:
    analytics: UA-42961666-3
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: peachyo
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
